### PR TITLE
Add version selector to documentation

### PR DESCRIPTION
**Pull request by e-lo**
This PR adds the mike version selector to the documentation page so that the documentation version can be selected from a dropdown menu

By contributing to this project, all contributors certify to the Developer Certificate of Origin in [CONTRIBUTING.md](CONTRIBUTING.md#contributor-agreement).

### CODE REVIEW

**Comment by e-lo** [comment]
Updated to latest `main` think its ready to merge?

**Comment by botanize** [comment]
I'm not seeing any problems on your fork, https://e-lo.github.io/TIDES/add-mike-version-selector/, but I'm also not seeing a version selector. Does mike automatically pick-up tags, or do you have to manually name releases?

**Comment by e-lo** [comment]
Yeah, `mike` does it based on the name you give it when you push it, in this case `${{ env.Slug }}`

`mike deploy --push --rebase ${{ env.Slug }}`

**Review by botanize — APPROVED** [review]
E,
I noticed in the mike generated [documentation for bfg9000](https://github.com/jimporter/bfg9000/blob/master/mkdocs.yml), referenced in the mike README that they load extra css and js for the selector. Not sure if that's necessary or even desirable. To be honest, I thought I'd see a selector, even if the only option was "main".

Do we want to document somewhere that we'll need to tag commits or use branches to produce distinct versions of the documentation?

Since this PR doesn't break anything, I think you can go ahead and merge, and we can deal with my questions in additional PRs if needed.

**Pull request merged**
